### ISSUE TITLE
 cannot call others, while establishing a call ,it always return sip failure code

### ISSUE THREAD

**Issue by amosli** [versatica/tryit-jssip#3] opened 2016-12-20 09:32 UTC
Hi,Versatica:
I run this demo, cannot call others, while establishing a call ,it always return sip failure code.
When I click the button call ,it wait to establishing a call , but when it connect to  other phone ,it close the connection immediately, and return sip failure code.My account is right, I has do a right call with sip.js .

The chrome  browser console log as follows:
`
 +0ms
browser.js:119 JsSIP:WebSocketInterface send() +1ms
browser.js:119 JsSIP:RTCSession receiveInviteResponse() +1ms
browser.js:119 JsSIP:RTCSession session failed +1ms
browser.js:119 JsSIP:RTCSession close() +2ms
browser.js:119 JsSIP:RTCSession close() | closing local MediaStream +2ms
browser.js:119 JsSIP:Dialog dialog 0ro979uuoh33veti2tr7rbemvl1u12QvZKU8Ba5eU2p deleted +3ms
debug.js:127 tryit-jssip:audioPlayer stop() [name:ringback] +43ms
debug.js:127 tryit-jssip:audioPlayer play() [name:rejected, relativeVolume:1] +1ms
browser.js:119 JsSIP:InviteClientTransaction Timer D expired for transaction z9hG4bK4660533 +35ms`

**Comment by jmillan** [comment] 2016-12-20 09:42
Closing since this is not a bug. Please, analyse the SIP traces and check why you're getting a SIP failure code from your server.

Any question you may have please use the mailing [list](jssip@googlegroups.com) after having checked the logs and traces by yourself.

**Closed as completed by jmillan** 2016-12-20 09:42 UTC
